// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import ThemeSoundProvider from "@/components/ThemeSoundProvider";

export const metadata: Metadata = {
  title: "TypeLively - Playful & Premium Typing Test & Practice Platform",
  description: "Improve your typing speed and accuracy with TypeLively. Daily challenges, dynamic paragraphs generated by Groq AI, real leaderboards, and coding exercises.",
  keywords: "typing test, typing practice, wpm calculator, daily typing challenge, coding typing test, learn typing, english typing, hindi typing, gujarati typing",
  openGraph: {
    title: "TypeLively - Playful & Premium Typing Platform",
    description: "Improve your typing speed with daily challenges and AI-generated passages. Free, addictively fun, and competitive.",
    type: "website",
    url: "https://typelively.vercel.app",
  },
  twitter: {
    card: "summary_large_image",
    title: "TypeLively - Premium Typing Platform",
    description: "Compete in daily typing challenges and practice coding syntax typing.",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Inline script to prevent theme flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedTheme = localStorage.getItem('typelively-theme');
                  const theme = savedTheme === 'dark' ? 'dark' : 'light';
                  document.documentElement.setAttribute('data-theme', theme);
                } catch (e) {
                  document.documentElement.setAttribute('data-theme', 'light');
                }
              })();
            `,
          }}
        />
      </head>
      <body>
        <ThemeSoundProvider>
          {/* Skip link for keyboard accessibility */}
          <a href="#main-content" className="skip-link">
            Skip to main content
          </a>

          <header>
            <div className="container header-inner">
              <Link href="/" className="logo" aria-label="TypeLively Home">
                <span className="logo-icon" aria-hidden="true">🎯</span>
                <span>TypeLively</span>
              </Link>

              <nav aria-label="Main Navigation">
                <Link href="/practice">Practice</Link>
                <Link href="/daily">Daily Challenge</Link>
                <Link href="/coding">Coding</Link>
                <Link href="/blog">Guides</Link>
                <Link href="/about">About</Link>
              </nav>

              {/* Theme and Sound Toggles (Rendered Client-side) */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }} id="controls-slot" />
            </div>
          </header>

          <main id="main-content" style={{ flex: 1 }}>
            {children}
          </main>

          <footer>
            <div className="container">
              <div className="footer-grid">
                <div className="footer-col">
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <span>🎯</span> TypeLively
                  </h4>
                  <p style={{ fontSize: '0.9rem', lineHeight: '1.5', marginTop: '0.5rem' }}>
                    The addictive typing arena built for coders, writers, and keyboard enthusiasts. Enhance your speed, master layouts, and climb the daily leaderboards.
                  </p>
                </div>
                <div className="footer-col">
                  <h4>Typing Tests</h4>
                  <ul>
                    <li><Link href="/typing-tests/1-minute-typing-test">1 Minute Test</Link></li>
                    <li><Link href="/typing-tests/3-minute-typing-test">3 Minute Test</Link></li>
                    <li><Link href="/typing-tests/5-minute-typing-test">5 Minute Test</Link></li>
                    <li><Link href="/typing-tests/1-page-typing-test">1 Page Test</Link></li>
                  </ul>
                </div>
                <div className="footer-col">
                  <h4>Specialized Practice</h4>
                  <ul>
                    <li><Link href="/coding">Coding Practice</Link></li>
                    <li><Link href="/typing-tests/python-typing-test">Python Syntax</Link></li>
                    <li><Link href="/typing-tests/javascript-typing-test">JavaScript Syntax</Link></li>
                    <li><Link href="/practice">Multilingual Practice</Link></li>
                  </ul>
                </div>
                <div className="footer-col">
                  <h4>Legal & Info</h4>
                  <ul>
                    <li><Link href="/about">About Us</Link></li>
                    <li><Link href="/contact">Contact</Link></li>
                    <li><Link href="/privacy">Privacy Policy</Link></li>
                    <li><Link href="/terms">Terms of Service</Link></li>
                  </ul>
                </div>
              </div>
              <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '1.5rem', textAlign: 'center', fontSize: '0.85rem' }}>
                <p>&copy; {new Date().getFullYear()} TypeLively. Built for speed, security, and typographic glory.</p>
              </div>
            </div>
          </footer>
        </ThemeSoundProvider>
      </body>
    </html>
  );
}
